spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/${DBNAME}?serverTimezone=Asia/Seoul
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  header: ${HEADER}
  prefix: ${PREFIX}
  secret: ${SECRET}
  exp:
    access: ${ACCESS}
    refresh: ${REFRESH}