spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:mysql://${DBURL}:3306/${DBNAME}?serverTimezone=Asia/Seoul
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

cloud:
  aws:
    credentials:
      accessKey: AKIAQYAPUX5DIOMSJVXC
      secretKey: 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
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


