spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size:

  datasource:
    url:
    username:
    password:
    driver-class-name:

jwt:
  secret-key:
  access-exp:
  refresh-exp:
  header:
  prefix:

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
    region:
      static:
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error



${JWT_ACCESS_EXP}:
${JWT_REFRESH_EXP}:
${JWT_SECRET}:
${JWT_HEADER}:
${JWT_PREFIX}: