spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/${DBNAME}?serverTimezone=Asia/Seoul
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}